"""统一关键词别名表：匹配用 ALIASES + 搜索用 SEARCH_QUERIES + 分类 CATEGORIES。"""

from __future__ import annotations

# ── 匹配别名（中文 → 英文 tag 集合，供 footage.py 匹配用） ─────────
ALIASES: dict[str, set[str]] = {
    # 科技 / AI
    "芯片": {"chip", "hardware"},
    "代码": {"code", "programming"},
    "机器人": {"robot"},
    "数据": {"data"},
    "人工智能": {"ai"},
    "模型": {"ai", "model"},
    "界面": {"ui", "interface"},
    "搜索": {"search"},
    # 产品/品牌 → ai（key 必须小写，因 match_footage tokens 已 lower）
    "claude": {"ai"},
    "gpt": {"ai"},
    "chatgpt": {"ai"},
    "openai": {"ai"},
    "多模态": {"ai"},
    # 文档/数据 → data
    "pdf": {"data"},
    "网络": {"network", "internet"},
    "自动化": {"automation"},
    "深度学习": {"ai", "deep-learning"},
    "大模型": {"ai", "llm", "model"},
    "生成式": {"ai", "generative"},
    "对话": {"ai", "chat"},
    "提示词": {"ai", "prompt"},
    "训练": {"ai", "training"},
    "推理": {"ai", "inference"},
    "算力": {"ai", "gpu", "computing"},
    "部署": {"ai", "deployment"},
    "开源": {"open-source", "github"},
    "GPU": {"gpu", "hardware"},
    "自动驾驶": {"ai", "autonomous"},
    "无人机": {"drone", "tech"},
    "VR": {"vr", "virtual-reality"},
    "AR": {"ar", "augmented-reality"},
    "物联网": {"iot", "internet"},
    # 浏览器 / 交互
    "浏览器": {"browser", "internet", "web"},
    "鼠标": {"mouse", "data", "interface"},
    "键盘": {"keyboard", "code"},
    "点击": {"interface", "ui"},
    "操作": {"interface", "automation"},
    "插件": {"code", "plugin"},
    "图标": {"ui", "interface"},
    "表单": {"data", "interface"},
    "填写": {"data", "automation"},
    "页面": {"web", "internet"},
    "下单": {"automation", "data"},
    # 语音 / AI 交互
    "语音": {"ai", "voice"},
    "指令": {"code", "automation"},
    "科技": {"ai", "tech"},
    "公司": {"ai", "tech"},
    "阅读": {"data", "ai"},
    "流程": {"data", "automation"},
    "logo": {"ai", "tech"},
    # 生活 / 场景
    "会议": {"meeting", "conference"},
    "工作": {"work", "office"},
    "学习": {"studying", "learning"},
    "城市": {"city", "skyline"},
    "交通": {"traffic", "transportation"},
    "医院": {"hospital", "medical"},
    "学校": {"school", "education"},
    "工厂": {"factory", "manufacturing"},
    "实验室": {"laboratory", "science"},
    "超市": {"supermarket", "shopping"},
    "餐厅": {"restaurant", "food"},
    "健身房": {"gym", "fitness"},
    "机场": {"airport", "travel"},
    "银行": {"bank", "finance"},
    "图书馆": {"library", "books"},
    "发布会": {"launch", "event"},
    "办公": {"office", "work"},
    "手机": {"smartphone"},
    "电脑": {"computer"},
    "服务器": {"server"},
    # 人物 / 动作
    "程序员": {"programmer", "developer"},
    "工程师": {"engineer"},
    "医生": {"doctor", "medical"},
    "学生": {"student", "learning"},
    "演讲": {"presentation", "speech"},
    "握手": {"handshake", "deal"},
    "讨论": {"discussion", "team"},
    "思考": {"thinking", "brain"},
    "庆祝": {"celebration"},
    # 抽象 / 概念
    "未来": {"futuristic"},
    "创新": {"innovation"},
    "增长": {"growth", "chart"},
    "安全": {"security", "shield"},
    "连接": {"connection", "network"},
    "竞争": {"competition"},
    "合作": {"partnership", "cooperation"},
    "效率": {"efficiency", "productivity"},
    "隐私": {"privacy", "protection"},
    "算法": {"algorithm"},
    "区块链": {"blockchain"},
    "量子": {"quantum", "computing"},
}

# ── 搜索查询词（中文 → 英文搜索词，供 stock.py API 搜索用） ─────────
SEARCH_QUERIES: dict[str, str] = {
    # 科技 / AI
    "发布会": "launch event",
    "办公": "office work",
    "手机": "smartphone",
    "电脑": "computer",
    "服务器": "server",
    "芯片": "chip semiconductor",
    "代码": "coding programming",
    "机器人": "robot",
    "数据": "data visualization",
    "人工智能": "artificial intelligence",
    "模型": "AI model",
    "界面": "user interface",
    "搜索": "search engine",
    "网络": "network internet",
    "自动化": "automation",
    "浏览器": "web browser",
    "鼠标": "computer mouse",
    "键盘": "keyboard typing",
    "点击": "click interface",
    "操作": "interface automation",
    "插件": "plugin code",
    "图标": "icon UI",
    "表单": "form data",
    "填写": "form filling",
    "页面": "web page",
    "下单": "online shopping",
    "语音": "voice AI",
    "指令": "command code",
    "科技": "technology",
    "公司": "company tech",
    "阅读": "reading data",
    "流程": "workflow automation",
    "logo": "logo brand",
    "深度学习": "deep learning neural network",
    "大模型": "large language model AI",
    "生成式": "generative AI",
    "对话": "conversation chat AI",
    "提示词": "prompt engineering AI",
    "训练": "AI model training",
    "推理": "AI inference computing",
    "算力": "GPU computing power",
    "部署": "AI deployment server",
    "开源": "open source code github",
    "GPU": "GPU graphics card",
    "自动驾驶": "autonomous driving self-driving",
    "无人机": "drone aerial",
    "VR": "virtual reality VR headset",
    "AR": "augmented reality AR glasses",
    "物联网": "internet of things IoT",
    # 生活 / 场景
    "会议": "meeting conference",
    "工作": "work office",
    "学习": "studying learning",
    "城市": "city skyline",
    "交通": "traffic transportation",
    "医院": "hospital medical",
    "学校": "school education",
    "工厂": "factory manufacturing",
    "实验室": "laboratory science",
    "超市": "supermarket shopping",
    "餐厅": "restaurant food",
    "健身房": "gym fitness",
    "机场": "airport travel",
    "银行": "bank finance",
    "图书馆": "library books",
    # 人物 / 动作
    "程序员": "programmer developer",
    "工程师": "engineer",
    "医生": "doctor medical",
    "学生": "student learning",
    "演讲": "presentation speech",
    "握手": "handshake deal",
    "讨论": "discussion team",
    "思考": "thinking brain",
    "庆祝": "celebration",
    # 抽象 / 概念
    "未来": "futuristic",
    "创新": "innovation",
    "增长": "growth chart",
    "安全": "security shield",
    "连接": "connection network",
    "竞争": "competition",
    "合作": "partnership cooperation",
    "效率": "efficiency productivity",
    "隐私": "privacy protection",
    "算法": "algorithm",
    "区块链": "blockchain",
    "量子": "quantum computing",
}

# ── 分类（英文 tag → 分类目录） ────────────────────────────────────
CATEGORIES: dict[str, str] = {
    # tech
    "ai": "tech", "model": "tech", "llm": "tech", "deep-learning": "tech",
    "generative": "tech", "chat": "tech", "prompt": "tech", "training": "tech",
    "inference": "tech", "gpu": "tech", "computing": "tech", "deployment": "tech",
    "open-source": "tech", "github": "tech", "autonomous": "tech", "drone": "tech",
    "vr": "tech", "virtual-reality": "tech", "ar": "tech", "augmented-reality": "tech",
    "iot": "tech", "internet": "tech", "chip": "tech", "hardware": "tech",
    "code": "tech", "programming": "tech", "server": "tech", "computer": "tech",
    "smartphone": "tech", "browser": "tech", "web": "tech", "plugin": "tech",
    "blockchain": "tech", "quantum": "tech", "algorithm": "tech",
    # abstract
    "data": "abstract", "automation": "abstract", "interface": "abstract", "ui": "abstract",
    "network": "abstract", "security": "abstract", "privacy": "abstract",
    "connection": "abstract", "efficiency": "abstract", "productivity": "abstract",
    "futuristic": "abstract", "innovation": "abstract", "growth": "abstract",
    "competition": "abstract", "partnership": "abstract", "cooperation": "abstract",
    # scene
    "office": "scene", "work": "scene", "meeting": "scene", "conference": "scene",
    "city": "scene", "skyline": "scene", "traffic": "scene", "transportation": "scene",
    "hospital": "scene", "medical": "scene", "school": "scene", "education": "scene",
    "factory": "scene", "manufacturing": "scene", "laboratory": "scene", "science": "scene",
    "supermarket": "scene", "shopping": "scene", "restaurant": "scene", "food": "scene",
    "gym": "scene", "fitness": "scene", "airport": "scene", "travel": "scene",
    "bank": "scene", "finance": "scene", "library": "scene", "books": "scene",
    "launch": "scene", "event": "scene",
    # people
    "robot": "people", "programmer": "people", "developer": "people",
    "engineer": "people", "doctor": "people", "student": "people",
    "presentation": "people", "speech": "people", "handshake": "people",
    "deal": "people", "discussion": "people", "team": "people",
    "thinking": "people", "brain": "people", "celebration": "people",
    "voice": "people", "mouse": "people", "keyboard": "people",
    "chart": "people", "shield": "people", "protection": "people",
}
